services:
  client:
    build: ./client
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    environment:
      - PORT=5000
    depends_on:
      - judge

  judge:
    build: ./judge
    volumes:
      - ./judge:/app
    tty: true